### ISSUE TITLE
The binary version after unpacking the .frk file is always 50% smaller than the original one.

### ISSUE THREAD

**Issue by AJM-DSC** [raphaelcoeffic/frk_tools#1]
Hi,

I tried using the programs you posted, Packer and Unpacker, for .frk files.
I haven't come across software that translates such files before, and I think they can be handy
- I am also an R/C modeler and use TX16S and FrSky equipment.
I'm not a Python specialist, so my comments come from observing how these programs work.
The unpacker program converts the .frk file to a binary version, but the resulting file is always 50% smaller than the original one.
The .bin file created in this way, after being "packed" again by the packer, gives a file with entirely different content from the original .frk file.

Are my problems due to misuse of these tools?
I'm using Python 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)] on win32

You can reply to my private email: biuro@dsc.com.pl

Andrzej
P.S.
Have you also analyzed .frsk files?

**Comment by raphaelcoeffic** [comment]
What you're seeing is absolutely normal. This is due to the way the original payload is scrambled and included into special frames that include some metadata.

The fact that packed files might be different from the unpacked one is not an issue. The metadata in the `.frk` embeds the PRNG seed used by the descrambler located in FrSky's boot loader.

> Have you also analyzed .frsk files?

Yes, all you need is to strip the description header. This format is described [here](https://github.com/EdgeTX/edgetx/blob/main/radio/src/io/frsky_firmware_update.h).

**Comment by AJM-DSC** [comment]
Hi Raphael,

 

Thank you for your quick reply and explanation.

I naively thought that the unpacked .bin file would be a complete image of what the scrambled .frk file contained. I was wondering why a 2kB block was read from the input file and only 1kB was written. I still don't know it yet!

The header of the (unpacked) binary file contains reference addresses that go beyond the length of the file - something is missing, but I don't know how to recreate the missing half of the data.

I was going to use the .bin file to re-flash the microcontroller from the sensor in which the STM32 processor was damaged. I replaced the integrated circuit, but the original STM32 does not have a bootloader to decode the batch.

Do you see any option to solve this problem?

Any help will be invaluable.

If you need any data about my observations, please let me know.

 

Andrzej

**Comment by raphaelcoeffic** [comment]
@AJM-DSC without the original bootloader or some deep knowledge on how to replace it, you're pretty much toast. The FW relies on the fact it runs at a specific address in FLASH, which is not the start address. Apart from that, I believe you will want to be able to flash it again, this time using the "normal" method via the bootloader, right?

FYI, I published this code for compatibility purposes, which enabled several open source projects to produce compatible firmwares with FrSky's bootloader. I don't intend on going for a full disclosure of all of FrSky's internals. You should be able to understand it out of the code. I you cannot, frankly, I cannot go further than that.

**Comment by AJM-DSC** [comment]
Hi Raphael,

 

Thanks again for your advice. 

I understand your position and decision perfectly. 

I'll work on it some more, but this path is probably a dead end 

and it's better to focus on solving more useful problems. 

IP is too valuable! Thank you and I wish you further success.

 

Andrzej
